# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "Rox"
repo_name: "cv-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 40

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "SLAM": 
        filters: ["SLAM", "Visual Odometry"]
    "BEV": 
        filters: ["Bird Eye View", "BEV SLAM", "BEV Localization", "BEV place recognition"]
    "Relocalization":
        filters: ["Place Recognition", "Re-localization", "Relocalization"]
    "Registration": 
        filters: ["pointcloud registration", "visual registration"]
    "Localization":
        filters: ["Visual Localization","Camera Localization",
                  "Camera Re-localization","Loop Closure Detection",
                  "place recognition","pointcloud localization"]
    "Feature":
        filters: ["Keypoint Detection", "semantic feature descriptor", "Feature Descriptor"]
    "Matching":
        filters: ["Image Matching", "Keypoint Matching", "pointcloud Matching", 
                  "Line Segment Detection", "Local Feature Matching"]
    "SFM":
        filters: ["SFM", "Structure from Motion"]
    "IMU":
        filters: ["IMU deep", "IMU learning", "inertial deep", "inertial learning", "deep IMU", "learning IMU", "deep inertial", "learning inertial"]
    "Transformer":
        filters: ["IMU transformer", "inertial transformer", "odometry transformer", "transformer IMU", "transformer inertial", "transformer odometry", "lidar transformer", "transformer lidar"]
    "NeRF":
        filters: ["NeRF"]
    "Occupancy Map":
        filters: ["occupancy grid", "occupancy map"]
    "Occupancy Predict":
        filters: ["occupancy predict"]

